[".vim/bundle/indentLine"]
  type = "git-repo"
  url = "https://github.com/Yggdroot/indentLine.git"
[".vim/bundle/vim-json"]
  type = "git-repo"
  url = "https://github.com/elzr/vim-json.git"
[".vim/bundle/vim-puppet"]
  type = "git-repo"
  url = "https://github.com/rodjek/vim-puppet.git"
[".vim/bundle/dash.vim"]
  type = "git-repo"
  url = "https://github.com/rizzatti/dash.vim.git"
[".vim/bundle/lightline.vim"]
  type = "git-repo"
  url = "https://github.com/itchyny/lightline.vim.git"
[".vim/bundle/lightline-bufferline"]
  type = "git-repo"
  url = "https://github.com/mgee/lightline-bufferline.git"
[".vim/bundle/onedark.vim"]
  type = "git-repo"
  url = "https://github.com/joshdick/onedark.vim.git"
[".vim/bundle/vim-gitgutter"]
  type = "git-repo"
  url = "https://github.com/airblade/vim-gitgutter.git"
[".vim/bundle/vim-commentary"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-commentary.git"
[".vim/bundle/vim-rails"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-rails.git"
[".vim/bundle/lightline-ale"]
  type = "git-repo"
  url = "https://github.com/maximbaz/lightline-ale.git"
[".vim/bundle/ale"]
  type = "git-repo"
  url = "https://github.com/w0rp/ale.git"
[".vim/bundle/vim-fugitive"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-fugitive.git"
[".vim/bundle/vim-bundler"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-bundler.git"
[".vim/bundle/vim-dispatch"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-dispatch.git"
[".vim/bundle/vim-pathogen"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-pathogen.git"
[".vim/bundle/vim-terraform"]
  type = "git-repo"
  url = "https://github.com/hashivim/vim-terraform.git"
[".vim/bundle/fzf.vim"]
  type = "git-repo"
  url = "https://github.com/junegunn/fzf.vim.git"
[".vim/bundle/vim-go"]
  type = "git-repo"
  url = "https://github.com/fatih/vim-go.git"
[".vim/bundle/fzf"]
  type = "git-repo"
  url = "https://github.com/junegunn/fzf.git"
[".vim/bundle/vim-vinegar"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-vinegar.git"
[".vim/bundle/vim-surround"]
  type = "git-repo"
  url = "https://github.com/tpope/vim-surround.git"
[".vim/bundle/vim-prettier"]
  type = "git-repo"
  url = "https://github.com/prettier/vim-prettier.git"
[".vim/bundle/vim-base64"]
  type = "git-repo"
  url = "https://github.com/christianrondeau/vim-base64.git"
[".vim/bundle/copilot.vim"]
  type = "git-repo"
  url = "https://github.com/github/copilot.vim.git"
