"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character
"""

[username]
style_user = 'bold green'
show_always = true
format = '[\[](bold)[$user]($style)[@](bold)'

[hostname]
style = 'bold yellow'
ssh_only = false
format = '[$hostname]($style)[:](bold)'

[directory]
style = 'bold blue'
format = '[$path]($style)[$read_only]($read_only_style)[\]](bold) '
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)\] '

[git_branch]
style = 'bold green'
format = '[\[](bold)[$symbol$branch(:$remote_branch)]($style)[\]](bold) '

[git_status]
style = 'bold'
conflicted = '='
ahead = '[⇡](blue)'
behind = '[⇣](red)'
diverged = '⇕'
untracked = '[?](cyan) '
stashed = '\$'
modified = '[!](yellow) '
staged = '[+](green) '
renamed = '»'
deleted = '[✘](red) '
format = '([$all_status$ahead_behind]($style) )'

[character]
success_symbol = '%'
error_symbol = '[%](red)'
